apiVersion: v1
kind: ConfigMap
metadata:
  name: oxtrust-cm
  namespace: gluu
data:
  GLUU_CONFIG_ADAPTER: "kubernetes"
  GLUU_SECRET_ADAPTER: "kubernetes"
  DOMAIN: "demoexample.gluu.org"
  GLUU_LDAP_URL: "opendj:1636"
  GLUU_SECRET_KUBERNETES_NAMESPACE: "gluu"
  GLUU_CONFIG_KUBERNETES_NAMESPACE: "gluu"
  GLUU_OXAUTH_BACKEND: "oxauth:8080"

---

apiVersion: v1
kind: Service
metadata:
  name: oxtrust
  labels:
    app: oxtrust
  namespace: gluu
spec:
  ports:
  - port: 8080
    name: oxtrust
  selector:
    app: oxtrust

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oxtrust
  labels:
    app: oxtrust
  namespace: gluu
spec:
  serviceName: oxtrust
  replicas: 1
  selector:
    matchLabels:
      app: oxtrust
  template:
    metadata:
      labels:
        app: oxtrust
      namespace: gluu
    spec:
      containers:
      - name: oxtrust
        # imagePullPolicy: Always
        image: docker.io/gluufederation/oxtrust:4.2.2_dev
        resources:
          requests:
            memory: "1000Mi"
          limits:
            memory: "1536Mi"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: oxtrust-cm
        # livenessProbe:
        #   httpGet:
        #     path: /oxtrust/.well-known/openid-configuration
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        # readinessProbe:
        #   httpGet:
        #     path: /oxtrust/.well-known/openid-configuration
        #     port: 8080
        #   initialDelaySeconds: 25
        #   periodSeconds: 25
      hostAliases:
      - ip: NGINX_IP
        hostnames:
        - demoexample.gluu.org
