apiVersion: v1
kind: ConfigMap
metadata:
  name: oxshibboleth-cm
  namespace: gluu
data:
  GLUU_CONFIG_ADAPTER: "kubernetes"
  GLUU_SECRET_ADAPTER: "kubernetes"
  DOMAIN: "demoexample.gluu.org"
  GLUU_LDAP_URL: "opendj:1636"
  GLUU_SECRET_KUBERNETES_NAMESPACE: "gluu"
  GLUU_CONFIG_KUBERNETES_NAMESPACE: "gluu"

---

apiVersion: v1
kind: Service
metadata:
  name: oxshibboleth
  labels:
    app: oxshibboleth
  namespace: gluu
spec:
  ports:
  - port: 8080
    name: oxshibboleth
  selector:
    app: oxshibboleth

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oxshibboleth
  labels:
    app: oxshibboleth
  namespace: gluu
spec:
  serviceName: oxshibboleth
  replicas: 1
  selector:
    matchLabels:
      app: oxshibboleth
  template:
    metadata:
      labels:
        app: oxshibboleth
      namespace: gluu
    spec:
      containers:
      - name: oxshibboleth
        # imagePullPolicy: Always
        image: docker.io/gluufederation/oxshibboleth:4.3.0_dev
        resources:
          requests:
            memory: "1000Mi"
          limits:
            memory: "1536Mi"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: oxshibboleth-cm
        # livenessProbe:
        #   httpGet:
        #     path: /oxshibboleth/.well-known/openid-configuration
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        # readinessProbe:
        #   httpGet:
        #     path: /oxshibboleth/.well-known/openid-configuration
        #     port: 8080
        #   initialDelaySeconds: 25
        #   periodSeconds: 25
      hostAliases:
      - ip: NGINX_IP
        hostnames:
        - demoexample.gluu.org
