apiVersion: v1
kind: ConfigMap
metadata:
  name: oxauth-cm
  namespace: gluu
data:
  GLUU_CONFIG_ADAPTER: "kubernetes"
  GLUU_SECRET_ADAPTER: "kubernetes"
  DOMAIN: "demoexample.gluu.org"
  GLUU_LDAP_URL: "opendj:1636"
  GLUU_SECRET_KUBERNETES_NAMESPACE: "gluu"
  GLUU_CONFIG_KUBERNETES_NAMESPACE: "gluu"

---

apiVersion: v1
kind: Service
metadata:
  name: oxauth
  labels:
    app: oxauth
  namespace: gluu
spec:
  ports:
  - port: 8080
    name: oxauth
  selector:
    app: oxauth

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxauth
  labels:
    app: oxauth
    APP_NAME: oxauth
  namespace: gluu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oxauth
  template:
    metadata:
      labels:
        app: oxauth
        APP_NAME: oxauth
      namespace: gluu
    spec:
      containers:
      - name: oxauth
        # imagePullPolicy: Always
        image: docker.io/gluufederation/oxauth:4.3.0_dev
        resources:
          requests:
            memory: "1000Mi"
          limits:
            memory: "1536Mi"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: oxauth-cm
        livenessProbe:
          httpGet:
            path: /oxauth/.well-known/openid-configuration
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /oxauth/.well-known/openid-configuration
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 25
      hostAliases:
      - ip: NGINX_IP
        hostnames:
        - demoexample.gluu.org
