apiVersion: v1
kind: ConfigMap
metadata:
  name: casa-cm
  namespace: gluu
data:
  GLUU_CONFIG_ADAPTER: "kubernetes"
  GLUU_SECRET_ADAPTER: "kubernetes"
  DOMAIN: "demoexample.gluu.org"
  GLUU_LDAP_URL: "opendj:1636"
  GLUU_SECRET_KUBERNETES_NAMESPACE: "gluu"
  GLUU_CONFIG_KUBERNETES_NAMESPACE: "gluu"
  GLUU_OXAUTH_BACKEND: "oxauth:8080"
  GLUU_OXD_SERVER_URL: "oxd:8443"

---

apiVersion: v1
kind: Service
metadata:
  name: casa
  labels:
    app: casa
  namespace: gluu
spec:
  ports:
  - port: 8080
    name: casa
  selector:
    app: casa

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: casa
  labels:
    app: casa
  namespace: gluu
spec:
  serviceName: casa
  replicas: 1
  selector:
    matchLabels:
      app: casa
  template:
    metadata:
      labels:
        app: casa
      namespace: gluu
    spec:
      containers:
      - name: casa
        # imagePullPolicy: Always
        image: docker.io/gluufederation/casa:4.3.0_dev
        resources:
          requests:
            memory: "1000Mi"
          limits:
            memory: "1536Mi"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: casa-cm
        # livenessProbe:
        #   httpGet:
        #     path: /casa/.well-known/openid-configuration
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        # readinessProbe:
        #   httpGet:
        #     path: /casa/.well-known/openid-configuration
        #     port: 8080
        #   initialDelaySeconds: 25
        #   periodSeconds: 25
      hostAliases:
      - ip: NGINX_IP
        hostnames:
        - demoexample.gluu.org
