apiVersion: v1
kind: ConfigMap
metadata:
  name: config-cm
  namespace: gluu
data:
  GLUU_CONFIG_ADAPTER: "kubernetes"
  GLUU_SECRET_ADAPTER: "kubernetes"
  GLUU_SECRET_KUBERNETES_NAMESPACE: "gluu"
  GLUU_CONFIG_KUBERNETES_NAMESPACE: "gluu"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-generate-params
  namespace: gluu
data:
  generate.json: |
    {
      "hostname": "demoexample.gluu.org",
      "country_code": "US",
      "state": "TX",
      "city": "Austin",
      "admin_pw": "S3cr3t+pass",
      "ldap_pw": "S3cr3t+pass",
      "email": "s@gluu.local",
      "org_name": "Gluu"
    }

---

apiVersion: batch/v1
kind: Job
metadata:
  name: config-load
  namespace: gluu
spec:
  template:
    metadata:
      labels:
        app: config-load
      namespace: gluu
    spec:
      restartPolicy: Never
      volumes:
        - name: config-generate-params
          configMap:
            name: config-generate-params
      containers:
        - name: config-load
          image: docker.io/gluufederation/config-init:4.3.0_dev
          volumeMounts:
            - mountPath: /app/db/generate.json
              name: config-generate-params
              subPath: generate.json
          envFrom:
          - configMapRef:
              name: config-cm
          args: ["load"]
