apiVersion: v1
kind: ConfigMap
metadata:
  name: jackrabbit-cm
  namespace: gluu
data:
  GLUU_CONFIG_ADAPTER: "kubernetes"
  GLUU_SECRET_ADAPTER: "kubernetes"
  DOMAIN: "demoexample.gluu.org"
  GLUU_SECRET_KUBERNETES_NAMESPACE: "gluu"
  GLUU_CONFIG_KUBERNETES_NAMESPACE: "gluu"

---

apiVersion: v1
kind: Service
metadata:
  name: jackrabbit
  labels:
    app: jackrabbit
  namespace: gluu
spec:
  ports:
  - port: 8080
    name: jackrabbit
  selector:
    app: jackrabbit

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jackrabbit
  labels:
    app: jackrabbit
  namespace: gluu
spec:
  serviceName: jackrabbit
  replicas: 1
  selector:
    matchLabels:
      app: jackrabbit
  template:
    metadata:
      labels:
        app: jackrabbit
      namespace: gluu
    spec:
      containers:
      - name: jackrabbit
        # imagePullPolicy: Always
        image: docker.io/gluufederation/jackrabbit:4.2.2_dev
        resources:
          requests:
            memory: "1000Mi"
          limits:
            memory: "1536Mi"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: jackrabbit-cm
        # livenessProbe:
        #   httpGet:
        #     path: /jackrabbit/.well-known/openid-configuration
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        # readinessProbe:
        #   httpGet:
        #     path: /jackrabbit/.well-known/openid-configuration
        #     port: 8080
        #   initialDelaySeconds: 25
        #   periodSeconds: 25
      hostAliases:
      - ip: NGINX_IP
        hostnames:
        - demoexample.gluu.org
